apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-demo
  template:
    metadata:
      labels:
        app: microservice-demo
    spec:
      containers:
      - name: microservice-demo
        image: nginx:latest
        ports:
        - containerPort: 80